export const remoteCopy = {
  title: 'Pay someone far away',
  contacts: 'Contacts',
  noContacts: 'No contacts yet. Ask your friend to share their pay link, then add it here.',
  addLink: 'Add from a pay link',
  scanLink: 'Point the camera at your friend’s pay link, or paste it.',
  paste: 'Paste a pay link',
  notALink: 'That is not a pay link for this app.',
  failed: 'The payment could not be made. Nothing was sent.',
  amount: 'Amount',
  review: 'Review',
  confirm: 'Pay',
  edit: 'Change',
  reviewLine:
    '{name} gets {amount} {symbol} in their wallet when a phone with internet passes it on. If none does before {deadline}, it is not paid and the money stays yours, in your lock.',
  notChecked:
    'Not checked: if their wallet cannot receive USDC, the payment is not delivered and the money stays yours after the deadline shown in the review.',
  noAccount:
    'Their wallet has no USDC account yet. Ask them to open the pay link screen and create it, then add the link again.',
  pendingWarning: 'A payment to this contact is still on its way. If you pay again, both can be paid.',
  privacy:
    'People nearby who pass it on cannot see who pays or how much. The Buckspay server sees the payment and the network of the phone that passed it on.',
  offlineNote: 'You are offline: a phone nearby with internet has to take it.',
  onlineNote: 'You are online: it is sent to the network now.',
  receiveTitle: 'Get paid from far away',
  receiveIntro: 'Share this so people can pay you from anywhere. It shows your wallet address and name.',
  name: 'Your name',
  share: 'Share',
  linkLabel: 'Your pay link as a QR code',
  needsAccount:
    'To be paid from far away you need a USDC account in your wallet. Creating it costs a small network fee.',
  createAccount: 'Create my USDC account',
  checking: 'Checking your USDC account…',
  status: {
    signed: 'Waiting for a phone nearby',
    received: 'Passed on',
    relaying: 'On its way',
    delivered: 'Delivered',
    expired: 'Not delivered, money kept',
    refused: 'Not paid',
  },
  received: 'Received {amount} {symbol} · {from}',
  detail: {
    status: 'Status',
    passed: 'Passed on',
    deadlineTitle: 'Payable until',
    passedTo: 'Passed to {count} phones nearby',
    passedToOne: 'Passed to 1 phone nearby',
    deadline: '{deadline}',
    expiredNote: 'No phone with internet passed it on in time. Nothing was paid; the money stays yours, in your lock.',
  },
  paidFar: 'Paid {amount} {symbol} · {payee} · {status}',
  someone: 'someone far away',
  from: 'From {name}',
  fromUnknown: 'From someone far away',
} as const
