skip_local_validator = true

[toolchain]
solana_version = "4.3.0"
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
buckspay = "zkJoXgVrQ8kvJGvnAYXGaF8KgT9pUKKExXF4zoF2eTM"

[provider]
cluster = "localnet"
wallet = "~/.config/buckspay/deployer.json"

[scripts]
test = "cargo test --features buckspay/devnet"

[hooks]
